// ADD
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

// UPDATE
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// get one user by email
export const GETBYEMAIL_USER = 'GETBYEMAIL_USER';
export const GETBYEMAIL_USER_SUCCESS = 'GETBYEMAIL_USER_SUCCESS';
export const GETBYEMAIL_USER_FAILURE = 'GETBYEMAIL_FAILURE';

// forget password
export const FORGETPASSWORD_USER = 'FORGETPASSWORD_USER';
export const FORGETPASSWORD_USER_SUCCESS = 'FORGETPASSWORD_USER_SUCCESS';
export const FORGETPASSWORD_USER_FAILURE = 'FORGETPASSWORD_USER_FAILURE';
// DELETE
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// GET ALL
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
// CHANGE password
export const CHANGEPASSWORD_USER = 'CHANGEPASSWORD_USER';
export const CHANGEPASSWORD_USER_SUCCESS = 'CHANGEPASSWORD_USER_SUCCESS';
export const CHANGEPASSWORD_USER_FAILURE = 'CHANGEPASSWORD_USER_FAILURE';