// ADD
export const ADD_CITY = 'ADD_CITY';
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS';
export const ADD_CITY_FAILURE = 'ADD_CITY_FAILURE';

// IMPORT
export const IMPORT_CITY = 'IMPORT_CITY';
export const IMPORT_CITY_SUCCESS = 'IMPORT_CITY_SUCCESS';
export const IMPORT_CITY_FAILURE = 'IMPORT_CITY_FAILURE';

// UPDATE
export const UPDATE_CITY = 'UPDATE_CITY';
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS';
export const UPDATE_CITY_FAILURE = 'UPDATE_CITY_FAILURE';

// DELETE
export const DELETE_CITY = 'DELETE_CITY';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const DELETE_CITY_FAILURE = 'DELETE_CITY_FAILURE';

// GET ALL
export const GET_ALL_CITYS = 'GET_ALL_CITYS';
export const GET_ALL_CITYS_SUCCESS = 'GET_ALL_CITYS_SUCCESS';
export const GET_ALL_CITYS_FAILURE = 'GET_ALL_CITYS_FAILURE';

// GET ALL cities BY state
export const GET_ALL_CITYBYSTATE = 'GET_ALL_CITYBYSTATE ';
export const GET_ALL_CITYBYSTATE_SUCCESS = 'GET_ALL_CITYBYSTATE _SUCCESS';
export const GET_ALL_CITYBYSTATE_FAILURE = 'GET_ALL_CITYBYSTATE _FAILURE';