// ADD REQUEST STATUS
export const ADD_REQUEST_STATUS = 'ADD_REQUEST_STATUS';
export const ADD_REQUEST_STATUS_FAILURE = 'ADD_REQUEST_STATUS_FAILURE';
export const ADD_REQUEST_STATUS_SUCCESS = 'ADD_REQUEST_STATUS_SUCCESS';

// UPDATE REQUEST STATUS
export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS';
export const UPDATE_REQUEST_STATUS_FAILURE = 'UPDATE_REQUEST_STATUS_FAILURE';
export const UPDATE_REQUEST_STATUS_SUCCESS = 'UPDATE_REQUEST_STATUS_SUCCESS';

// DELETE REQUEST STATUS
export const DELETE_REQUEST_STATUS = 'DELETE_REQUEST_STATUS';
export const DELETE_REQUEST_STATUS_FAILURE = 'DELETE_REQUEST_STATUS_FAILURE';
export const DELETE_REQUEST_STATUS_SUCCESS = 'DELETE_REQUEST_STATUS_SUCCESS';

// GET ALL REQUEST STATUS
export const GET_ALL_REQUEST_STATUS = 'GET_ALL_REQUEST_STATUS';
export const GET_ALL_REQUEST_STATUS_FAILURE = 'GET_ALL_REQUEST_STATUS_FAILURE';
export const GET_ALL_REQUEST_STATUS_SUCCESS = 'GET_ALL_REQUEST_STATUS_SUCCESS';
