// GET SUMMARIZED WEEKLY REPORT
export const GET_SUMMARIZED_WEEKLY_REPORT = 'GET_SUMMARIZED_WEEKLY_REPORT';
export const GET_SUMMARIZED_WEEKLY_REPORT_FAILURE = 'GET_SUMMARIZED_WEEKLY_REPORT_FAILURE';
export const GET_SUMMARIZED_WEEKLY_REPORT_SUCCESS = 'GET_SUMMARIZED_WEEKLY_REPORT_SUCCESS';

// GET TREE DATA
export const GET_EXTENDED_WEEKLY_REPORT = 'GET_EXTENDED_WEEKLY_REPORT';
export const GET_EXTENDED_WEEKLY_REPORT_FAILURE = 'GET_EXTENDED_WEEKLY_REPORT_FAILURE';
export const GET_EXTENDED_WEEKLY_REPORT_SUCCESS = 'GET_EXTENDED_WEEKLY_REPORT_SUCCESS';

// SAVE WEEKLY REPORT DATA
export const SAVE_WEEKLY_REPORT = 'SAVE_WEEKLY_REPORT';
export const SAVE_WEEKLY_REPORT_FAILURE = 'SAVE_WEEKLY_REPORT_FAILURE';
export const SAVE_WEEKLY_REPORT_SUCCESS = 'SAVE_WEEKLY_REPORT_SUCCESS';
