// ADD
export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';
export const ADD_ASSIGNMENT_SUCCESS = 'ADD_ASSIGNMENT_SUCCESS';
export const ADD_ASSIGNMENT_FAILURE = 'ADD_ASSIGNMENT_FAILURE';

// UPDATE
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';
export const UPDATE_ASSIGNMENT_SUCCESS = 'UPDATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT_FAILURE = 'UPDATE_ASSIGNMENT_FAILURE';

// DELETE
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';
export const DELETE_ASSIGNMENT_FAILURE = 'DELETE_ASSIGNMENT_FAILURE';

// GET ALL
export const GET_ALL_ASSIGNMENTS = 'GET_ALL_ASSIGNMENTS';
export const GET_ALL_ASSIGNMENTS_SUCCESS = 'GET_ALL_ASSIGNMENTS_SUCCESS';
export const GET_ALL_ASSIGNMENTS_FAILURE = 'GET_ALL_ASSIGNMENTS_FAILURE';

// GET ALL ASSIGNMENT BY STAFF
export const GET_ALL_ASSIGNMENTS_BY_STAFF = 'GET_ALL_ASSIGNMENTS_BY_STAFF';
export const GET_ALL_ASSIGNMENTS_BY_STAFF_SUCCESS = 'GET_ALL_ASSIGNMENTS_BY_STAFF_SUCCESS';
export const GET_ALL_ASSIGNMENTS_BY_STAFF_FAILURE = 'GET_ALL_ASSIGNMENTS_BY_STAFF_FAILURE';
