// DELETE
export const DELETE_STAFFCONTRACTHISTORY = 'DELETE_STAFFCONTRACTHISTORY';
export const DELETE_STAFFCONTRACTHISTORY_SUCCESS = 'DELETE_STAFFCONTRACTHISTORY_SUCCESS';
export const DELETE_STAFFCONTRACTHISTORY_FAILURE = 'DELETE_STAFFCONTRACTHISTORY_FAILURE';

// GET ALL
export const GET_ALL_STAFFCONTRACTHISTORIES = 'GET_ALL_STAFFCONTRACTHISTORIES';
export const GET_ALL_STAFFCONTRACTHISTORIES_SUCCESS = 'GET_ALL_STAFFCONTRACTHISTORIES_SUCCESS';
export const GET_ALL_STAFFCONTRACTHISTORIES_FAILURE = 'GET_ALL_STAFFCONTRACTHISTORIES_FAILURE';

// GET ALL BY STAFFCONTRACTHISTORY CONTRACT
export const GET_ALL_STAFFCONTRACTHISTORIES_BY_CONTRACT = 'GET_ALL_STAFFCONTRACTHISTORIES_BY_CONTRACT';
export const GET_ALL_STAFFCONTRACTHISTORIES_BY_CONTRACT_SUCCESS = 'GET_ALL_STAFFCONTRACTHISTORIES_BY_CONTRACT_SUCCESS';
export const GET_ALL_STAFFCONTRACTHISTORIES_BY_CONTRACT_FAILURE = 'GET_ALL_STAFFCONTRACTHISTORIES_BY_CONTRACT_FAILURE';
