
// SAVE PERSON TYPE
export const ADD_PERSON_TYPE = 'ADD_PERSON_TYPE';
export const ADD_PERSON_TYPE_FAILURE = 'ADD_PERSON_TYPE_FAILURE';
export const ADD_PERSON_TYPE_SUCCESS = 'ADD_PERSON_TYPE_SUCCESS';

// UPDATE PERSON TYPE
export const UPDATE_PERSON_TYPE = 'UPDATE_PERSON_TYPE';
export const UPDATE_PERSON_TYPE_FAILURE = 'UPDATE_PERSON_TYPE_FAILURE';
export const UPDATE_PERSON_TYPE_SUCCESS = 'UPDATE_PERSON_TYPE_SUCCESS';

// DELETE PERSON TYPE
export const DELETE_PERSON_TYPE = 'DELETE_PERSON_TYPE';
export const DELETE_PERSON_TYPE_FAILURE = 'DELETE_PERSON_TYPE_FAILURE';
export const DELETE_PERSON_TYPE_SUCCESS = 'DELETE_PERSON_TYPE_SUCCESS';

// GET ALL PERSON TYPES
export const GET_ALL_PERSON_TYPES = 'GET_ALL_PERSON_TYPES';
export const GET_ALL_PERSON_TYPES_FAILURE = 'GET_ALL_PERSON_TYPES_FAILURE';
export const GET_ALL_PERSON_TYPES_SUCCESS = 'GET_ALL_PERSON_TYPES_SUCCESS';
