// GET BUSINESS EXPENSES TYPES
export const GET_CURRENCY_TYPES = 'GET_CURRENCY_TYPES';
export const GET_CURRENCY_TYPES_FAILURE = 'GET_CURRENCY_TYPES_FAILURE';
export const GET_CURRENCY_TYPES_SUCCESS = 'GET_CURRENCY_TYPES_SUCCESS';
