// ADD
export const ADD_SELECTIONPROCESSINFORMATION = 'ADD_SELECTIONPROCESSINFORMATION';
export const ADD_SELECTIONPROCESSINFORMATION_SUCCESS = 'ADD_SELECTIONPROCESSINFORMATION_SUCCESS';
export const ADD_SELECTIONPROCESSINFORMATION_FAILURE = 'ADD_SELECTIONPROCESSINFORMATION_FAILURE';

// UPDATE
export const UPDATE_SELECTIONPROCESSINFORMATION = 'UPDATE_SELECTIONPROCESSINFORMATION';
export const UPDATE_SELECTIONPROCESSINFORMATION_SUCCESS = 'UPDATE_SELECTIONPROCESSINFORMATION_SUCCESS';
export const UPDATE_SELECTIONPROCESSINFORMATION_FAILURE = 'UPDATE_SELECTIONPROCESSINFORMATION_FAILURE';

// DELETE
export const DELETE_SELECTIONPROCESSINFORMATION = 'DELETE_SELECTIONPROCESSINFORMATION';
export const DELETE_SELECTIONPROCESSINFORMATION_SUCCESS = 'DELETE_SELECTIONPROCESSINFORMATION_SUCCESS';
export const DELETE_SELECTIONPROCESSINFORMATION_FAILURE = 'DELETE_SELECTIONPROCESSINFORMATION_FAILURE';

// GET ALL
export const GET_ALL_SELECTIONPROCESSINFORMATIONS = 'GET_ALL_SELECTIONPROCESSINFORMATIONS';
export const GET_ALL_SELECTIONPROCESSINFORMATIONS_SUCCESS = 'GET_ALL_SELECTIONPROCESSINFORMATIONS_SUCCESS';
export const GET_ALL_SELECTIONPROCESSINFORMATIONS_FAILURE = 'GET_ALL_SELECTIONPROCESSINFORMATIONS_FAILURE';
