// ADD
export const ADD_CLIENT_COMMERCIAL = 'ADD_CLIENT_COMMERCIAL';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';

// UPDATE
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILURE = 'UPDATE_CLIENT_FAILURE';

// DELETE
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAILURE = 'DELETE_CLIENT_FAILURE';

// GET ALL
export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS';
export const GET_ALL_CLIENTS_FAILURE = 'GET_ALL_CLIENTS_FAILURE';

// GET ALL CLIENT BY COUNTRY
export const GET_ALL_CLIENTS_BYCOUNTRY = 'GET_ALL_CLIENTS_BYCOUNTRY';
export const GET_ALL_CLIENTS_BYCOUNTRY_SUCCESS = 'GET_ALL_CLIENTS_BYCOUNTRY_SUCCESS';
export const GET_ALL_CLIENTS_BYCOUNTRY_FAILURE = 'GET_ALL_CLIENTS_BYCOUNTRY_FAILURE';

// IMPORT
export const IMPORT_CLIENT_COMMERCIAL = 'IMPORT_CLIENT_COMMERCIAL';
export const IMPORT_CLIENT_SUCCESS = 'IMPORT_CLIENT_SUCCESS';
export const IMPORT_CLIENT_FAILURE = 'IMPORT_CLIENT_FAILURE';
