// ADD EMAIL ADDRESS
export const ADD_EXPENSE_EMAIL_ADDRESS = 'ADD_EXPENSE_EMAIL_ADDRESS';
export const ADD_EXPENSE_EMAIL_ADDRESS_FAILURE = 'ADD_EXPENSE_EMAIL_ADDRESS_FAILURE';
export const ADD_EXPENSE_EMAIL_ADDRESS_SUCCESS = 'ADD_EXPENSE_EMAIL_ADDRESS_SUCCESS';

// UPDATE EMAIL ADDRESS
export const UPDATE_EXPENSE_EMAIL_ADDRESS = 'UPDATE_EXPENSE_EMAIL_ADDRESS';
export const UPDATE_EXPENSE_EMAIL_ADDRESS_FAILURE = 'UPDATE_EXPENSE_EMAIL_ADDRESS_FAILURE';
export const UPDATE_EXPENSE_EMAIL_ADDRESS_SUCCESS = 'UPDATE_EXPENSE_EMAIL_ADDRESS_SUCCESS';


// DELETE EMAIL ADDRESS
export const DELETE_EXPENSE_EMAIL_ADDRESS = 'DELETE_EXPENSE_EMAIL_ADDRESS';
export const DELETE_EXPENSE_EMAIL_ADDRESS_FAILURE = 'DELETE_EXPENSE_EMAIL_ADDRESS_FAILURE';
export const DELETE_EXPENSE_EMAIL_ADDRESS_SUCCESS = 'DELETE_EXPENSE_EMAIL_ADDRESS_SUCCESS';

// GET ALL EMAIL ADDRESSES
export const GET_ALL_EXPENSE_EMAIL_ADDRESSES = 'GET_ALL_EXPENSE_EMAIL_ADDRESSES';
export const GET_ALL_EXPENSE_EMAIL_ADDRESSES_FAILURE = 'GET_ALL_EXPENSE_EMAIL_ADDRESSES_FAILURE';
export const GET_ALL_EXPENSE_EMAIL_ADDRESSES_SUCCESS = 'GET_ALL_EXPENSE_EMAIL_ADDRESSES_SUCCESS';
