// ADD
export const ADD_CIVILITYTITLE = 'ADD_CIVILITYTITLE';
export const ADD_CIVILITYTITLE_SUCCESS = 'ADD_CIVILITYTITLE_SUCCESS';
export const ADD_CIVILITYTITLE_FAILURE = 'ADD_CIVILITYTITLE_FAILURE';

// UPDATE
export const UPDATE_CIVILITYTITLE = 'UPDATE_CIVILITYTITLE';
export const UPDATE_CIVILITYTITLE_SUCCESS = 'UPDATE_CIVILITYTITLE_SUCCESS';
export const UPDATE_CIVILITYTITLE_FAILURE = 'UPDATE_CIVILITYTITLE_FAILURE';

// DELETE
export const DELETE_CIVILITYTITLE = 'DELETE_CIVILITYTITLE';
export const DELETE_CIVILITYTITLE_SUCCESS = 'DELETE_CIVILITYTITLE_SUCCESS';
export const DELETE_CIVILITYTITLE_FAILURE = 'DELETE_CIVILITYTITLE_FAILURE';

// GET ALL
export const GET_ALL_CIVILITYTITLES = 'GET_ALL_CIVILITYTITLES';
export const GET_ALL_CIVILITYTITLES_SUCCESS = 'GET_ALL_CIVILITYTITLES_SUCCESS';
export const GET_ALL_CIVILITYTITLES_FAILURE = 'GET_ALL_CIVILITYTITLES_FAILURE';
