// ADD STAFF EXPENSE TYPE
export const ADD_STAFF_EXPENSE_TYPE = 'ADD_STAFF_EXPENSE_TYPE';
export const ADD_STAFF_EXPENSE_TYPE_FAILURE = 'ADD_STAFF_EXPENSE_TYPE_FAILURE';
export const ADD_STAFF_EXPENSE_TYPE_SUCCESS = 'ADD_STAFF_EXPENSE_TYPE_SUCCESS';

// UPDATE STAFF EXPENSE TYPE
export const UPDATE_STAFF_EXPENSE_TYPE = 'UPDATE_STAFF_EXPENSE_TYPE';
export const UPDATE_STAFF_EXPENSE_TYPE_FAILURE = 'UPDATE_STAFF_EXPENSE_TYPE_FAILURE';
export const UPDATE_STAFF_EXPENSE_TYPE_SUCCESS = 'UPDATE_STAFF_EXPENSE_TYPE_SUCCESS';

// DELETE STAFF EXPENSE TYPE
export const DELETE_STAFF_EXPENSE_TYPE = 'DELETE_STAFF_EXPENSE_TYPE';
export const DELETE_STAFF_EXPENSE_TYPE_FAILURE = 'DELETE_STAFF_EXPENSE_TYPE_FAILURE';
export const DELETE_STAFF_EXPENSE_TYPE_SUCCESS = 'DELETE_STAFF_EXPENSE_TYPE_SUCCESS';

// GET STAFF EXPENSES TYPES
export const GET_STAFF_EXPENSES_TYPES = 'GET_STAFF_EXPENSES_TYPES';
export const GET_STAFF_EXPENSES_TYPES_FAILURE = 'GET_STAFF_EXPENSES_TYPES_FAILURE';
export const GET_STAFF_EXPENSES_TYPES_SUCCESS = 'GET_STAFF_EXPENSES_TYPES_SUCCESS';

//---------------------------------------------------------------------------------------------

// ADD STAFF EXPENSE SUBTYPE
export const ADD_STAFF_EXPENSE_SUBTYPE = 'ADD_STAFF_EXPENSE_SUBTYPE';
export const ADD_STAFF_EXPENSE_SUBTYPE_FAILURE = 'ADD_STAFF_EXPENSE_SUBTYPE_FAILURE';
export const ADD_STAFF_EXPENSE_SUBTYPE_SUCCESS = 'ADD_STAFF_EXPENSE_SUBTYPE_SUCCESS';

// UPDATE STAFF EXPENSE SUBTYPE
export const UPDATE_STAFF_EXPENSE_SUBTYPE = 'UPDATE_STAFF_EXPENSE_SUBTYPE';
export const UPDATE_STAFF_EXPENSE_SUBTYPE_FAILURE = 'UPDATE_STAFF_EXPENSE_SUBTYPE_FAILURE';
export const UPDATE_STAFF_EXPENSE_SUBTYPE_SUCCESS = 'UPDATE_STAFF_EXPENSE_SUBTYPE_SUCCESS';

// DELETE STAFF EXPENSE SUBTYPE
export const DELETE_STAFF_EXPENSE_SUBTYPE = 'DELETE_STAFF_EXPENSE_SUBTYPE';
export const DELETE_STAFF_EXPENSE_SUBTYPE_FAILURE = 'DELETE_STAFF_EXPENSE_SUBTYPE_FAILURE';
export const DELETE_STAFF_EXPENSE_SUBTYPE_SUCCESS = 'DELETE_STAFF_EXPENSE_SUBTYPE_SUCCESS';
