// ADD
export const ADD_CONTRACTMODEL = 'ADD_CONTRACTMODEL';
export const ADD_CONTRACTMODEL_SUCCESS = 'ADD_CONTRACTMODEL_SUCCESS';
export const ADD_CONTRACTMODEL_FAILURE = 'ADD_CONTRACTMODEL_FAILURE';

// UPDATE
export const UPDATE_CONTRACTMODEL = 'UPDATE_CONTRACTMODEL';
export const UPDATE_CONTRACTMODEL_SUCCESS = 'UPDATE_CONTRACTMODEL_SUCCESS';
export const UPDATE_CONTRACTMODEL_FAILURE = 'UPDATE_CONTRACTMODEL_FAILURE';

// DELETE
export const DELETE_CONTRACTMODEL = 'DELETE_CONTRACTMODEL';
export const DELETE_CONTRACTMODEL_SUCCESS = 'DELETE_CONTRACTMODEL_SUCCESS';
export const DELETE_CONTRACTMODEL_FAILURE = 'DELETE_CONTRACTMODEL_FAILURE';

// GET ALL
export const GET_ALL_CONTRACTMODELS = 'GET_ALL_CONTRACTMODELS';
export const GET_ALL_CONTRACTMODELS_SUCCESS = 'GET_ALL_CONTRACTMODELS_SUCCESS';
export const GET_ALL_CONTRACTMODELS_FAILURE = 'GET_ALL_CONTRACTMODELS_FAILURE';
