// ADD
export const ADD_STATECOUNTRY = 'ADD_STATECOUNTRY';
export const ADD_STATECOUNTRY_SUCCESS = 'ADD_STATECOUNTRY_SUCCESS';
export const ADD_STATECOUNTRY_FAILURE = 'ADD_STATECOUNTRY_FAILURE';

// UPDATE
export const UPDATE_STATECOUNTRY = 'UPDATE_STATECOUNTRY';
export const UPDATE_STATECOUNTRY_SUCCESS = 'UPDATE_STATECOUNTRY_SUCCESS';
export const UPDATE_STATECOUNTRY_FAILURE = 'UPDATE_STATECOUNTRY_FAILURE';

// DELETE
export const DELETE_STATECOUNTRY = 'DELETE_STATECOUNTRY';
export const DELETE_STATECOUNTRY_SUCCESS = 'DELETE_STATECOUNTRY_SUCCESS';
export const DELETE_STATECOUNTRY_FAILURE = 'DELETE_STATECOUNTRY_FAILURE';

// GET ALL
export const GET_ALL_STATECOUNTRYS = 'GET_ALL_STATECOUNTRYS';
export const GET_ALL_STATECOUNTRYS_SUCCESS = 'GET_ALL_STATECOUNTRYS_SUCCESS';
export const GET_ALL_STATECOUNTRYS_FAILURE = 'GET_ALL_STATECOUNTRYS_FAILURE';

// GET ALL STATE BY COUNTRY
export const GET_ALL_STATECOUNTRYSBYCOUNTRY = 'GET_ALL_STATECOUNTRYSBYCOUNTRY';
export const GET_ALL_STATECOUNTRYSBYCOUNTRY_SUCCESS = 'GET_ALL_STATECOUNTRYSBYCOUNTRY_SUCCESS';
export const GET_ALL_STATECOUNTRYSBYCOUNTRY_FAILURE = 'GET_ALL_STATECOUNTRYSBYCOUNTRY_FAILURE';
