// ADD
export const ADD_FUNCTIONALSTRUCTURELEVEL = 'ADD_FUNCTIONALSTRUCTURELEVEL';
export const ADD_FUNCTIONALSTRUCTURELEVEL_SUCCESS = 'ADD_FUNCTIONALSTRUCTURELEVEL_SUCCESS';
export const ADD_FUNCTIONALSTRUCTURELEVEL_FAILURE = 'ADD_FUNCTIONALSTRUCTURELEVEL_FAILURE';

// UPDATE
export const UPDATE_FUNCTIONALSTRUCTURELEVEL = 'UPDATE_FUNCTIONALSTRUCTURELEVEL';
export const UPDATE_FUNCTIONALSTRUCTURELEVEL_SUCCESS = 'UPDATE_FUNCTIONALSTRUCTURELEVEL_SUCCESS';
export const UPDATE_FUNCTIONALSTRUCTURELEVEL_FAILURE = 'UPDATE_FUNCTIONALSTRUCTURELEVEL_FAILURE';

// DELETE
export const DELETE_FUNCTIONALSTRUCTURELEVEL = 'DELETE_FUNCTIONALSTRUCTURELEVEL';
export const DELETE_FUNCTIONALSTRUCTURELEVEL_SUCCESS = 'DELETE_FUNCTIONALSTRUCTURELEVEL_SUCCESS';
export const DELETE_FUNCTIONALSTRUCTURELEVEL_FAILURE = 'DELETE_FUNCTIONALSTRUCTURELEVEL_FAILURE';

// GET ALL
export const GET_ALL_FUNCTIONALSTRUCTURELEVELS = 'GET_ALL_FUNCTIONALSTRUCTURELEVELS';
export const GET_ALL_FUNCTIONALSTRUCTURELEVELS_SUCCESS = 'GET_ALL_FUNCTIONALSTRUCTURELEVELS_SUCCESS';
export const GET_ALL_FUNCTIONALSTRUCTURELEVELS_FAILURE = 'GET_ALL_FUNCTIONALSTRUCTURELEVELS_FAILURE';

// GET ALL BY TYPE
export const GET_ALL_FUNCTIONALSTRUCTURELEVELS_BY_TYPE = 'GET_ALL_FUNCTIONALSTRUCTURELEVELS_BY_TYPE';
export const GET_ALL_FUNCTIONALSTRUCTURELEVELS_BY_TYPE_SUCCESS = 'GET_ALL_FUNCTIONALSTRUCTURELEVELS_BY_TYPE_SUCCESS';
export const GET_ALL_FUNCTIONALSTRUCTURELEVELS_BY_TYPE_FAILURE = 'GET_ALL_FUNCTIONALSTRUCTURELEVELS_BY_TYPE_FAILURE';
