// GET DATA BY CURRENCY TYPE
export const GET_DATA_BY_CURRENCY_TYPE = 'GET_DATA_BY_CURRENCY_TYPE';
export const GET_DATA_BY_CURRENCY_TYPE_FAILURE = 'GET_DATA_BY_CURRENCY_TYPE_FAILURE';
export const GET_DATA_BY_CURRENCY_TYPE_SUCCESS = 'GET_DATA_BY_CURRENCY_TYPE_SUCCESS';

// GET DATA ASSOCIATED WITH CURRENCY TYPES
export const GET_DATA_ASSOCIATED_WITH_CURRENCY_TYPES = 'GET_DATA_ASSOCIATED_WITH_CURRENCY_TYPES';
export const GET_DATA_ASSOCIATED_WITH_CURRENCY_TYPES_FAILURE = 'GET_DATA_ASSOCIATED_WITH_CURRENCY_TYPES_FAILURE';
export const GET_DATA_ASSOCIATED_WITH_CURRENCY_TYPES_SUCCESS = 'GET_DATA_ASSOCIATED_WITH_CURRENCY_TYPES_SUCCESS';
