// ADD
export const ADD_COMMERCIALOPERATIONSTATUS = 'ADD_COMMERCIALOPERATIONSTATUS';
export const ADD_COMMERCIALOPERATIONSTATUS_SUCCESS = 'ADD_COMMERCIALOPERATIONSTATUS_SUCCESS';
export const ADD_COMMERCIALOPERATIONSTATUS_FAILURE = 'ADD_COMMERCIALOPERATIONSTATUS_FAILURE';

// UPDATE
export const UPDATE_COMMERCIALOPERATIONSTATUS = 'UPDATE_COMMERCIALOPERATIONSTATUS';
export const UPDATE_COMMERCIALOPERATIONSTATUS_SUCCESS = 'UPDATE_COMMERCIALOPERATIONSTATUS_SUCCESS';
export const UPDATE_COMMERCIALOPERATIONSTATUS_FAILURE = 'UPDATE_COMMERCIALOPERATIONSTATUS_FAILURE';

// DELETE
export const DELETE_COMMERCIALOPERATIONSTATUS = 'DELETE_COMMERCIALOPERATIONSTATUS';
export const DELETE_COMMERCIALOPERATIONSTATUS_SUCCESS = 'DELETE_COMMERCIALOPERATIONSTATUS_SUCCESS';
export const DELETE_COMMERCIALOPERATIONSTATUS_FAILURE = 'DELETE_COMMERCIALOPERATIONSTATUS_FAILURE';

// GET ALL
export const GET_ALL_COMMERCIALOPERATIONSTATUSS = 'GET_ALL_COMMERCIALOPERATIONSTATUSS';
export const GET_ALL_COMMERCIALOPERATIONSTATUSS_SUCCESS = 'GET_ALL_COMMERCIALOPERATIONSTATUSS_SUCCESS';
export const GET_ALL_COMMERCIALOPERATIONSTATUSS_FAILURE = 'GET_ALL_COMMERCIALOPERATIONSTATUSS_FAILURE';
