// ADD
export const ADD_LEGALCATEGORYTYPE = 'ADD_LEGALCATEGORYTYPE';
export const ADD_LEGALCATEGORYTYPE_SUCCESS = 'ADD_LEGALCATEGORYTYPE_SUCCESS';
export const ADD_LEGALCATEGORYTYPE_FAILURE = 'ADD_LEGALCATEGORYTYPE_FAILURE';

// UPDATE
export const UPDATE_LEGALCATEGORYTYPE = 'UPDATE_LEGALCATEGORYTYPE';
export const UPDATE_LEGALCATEGORYTYPE_SUCCESS = 'UPDATE_LEGALCATEGORYTYPE_SUCCESS';
export const UPDATE_LEGALCATEGORYTYPE_FAILURE = 'UPDATE_LEGALCATEGORYTYPE_FAILURE';

// DELETE
export const DELETE_LEGALCATEGORYTYPE = 'DELETE_LEGALCATEGORYTYPE';
export const DELETE_LEGALCATEGORYTYPE_SUCCESS = 'DELETE_LEGALCATEGORYTYPE_SUCCESS';
export const DELETE_LEGALCATEGORYTYPE_FAILURE = 'DELETE_LEGALCATEGORYTYPE_FAILURE';

// GET ALL
export const GET_ALL_LEGALCATEGORYTYPES = 'GET_ALL_LEGALCATEGORYTYPES';
export const GET_ALL_LEGALCATEGORYTYPES_SUCCESS = 'GET_ALL_LEGALCATEGORYTYPES_SUCCESS';
export const GET_ALL_LEGALCATEGORYTYPES_FAILURE = 'GET_ALL_LEGALCATEGORYTYPES_FAILURE';

// GET ALL BY COMPANY
export const GET_ALL_LEGALCATEGORYTYPES_BY_COMPANY = 'GET_ALL_LEGALCATEGORYTYPES_BY_COMPANY';
export const GET_ALL_LEGALCATEGORYTYPES_BY_COMPANY_SUCCESS = 'GET_ALL_LEGALCATEGORYTYPES_BY_COMPANY_SUCCESS';
export const GET_ALL_LEGALCATEGORYTYPES_BY_COMPANY_FAILURE = 'GET_ALL_LEGALCATEGORYTYPES_BY_COMPANY_FAILURE';
