// ADD
export const ADD_SUBJECT_FIELD = 'ADD_SUBJECT_FIELD';
export const ADD_SUBJECT_FIELD_SUCCESS = 'ADD_SUBJECT_FIELD_SUCCESS';
export const ADD_SUBJECT_FIELD_FAILURE = 'ADD_SUBJECT_FIELD_FAILURE';

// UPDATE
export const UPDATE_SUBJECT_FIELD = 'UPDATE_SUBJECT_FIELD';
export const UPDATE_SUBJECT_FIELD_SUCCESS = 'UPDATE_SUBJECT_FIELD_SUCCESS';
export const UPDATE_SUBJECT_FIELD_FAILURE = 'UPDATE_SUBJECT_FIELD_FAILURE';

// DELETE
export const DELETE_SUBJECT_FIELD = 'DELETE_SUBJECT_FIELD';
export const DELETE_SUBJECT_FIELD_SUCCESS = 'DELETE_SUBJECT_FIELD_SUCCESS';
export const DELETE_SUBJECT_FIELD_FAILURE = 'DELETE_SUBJECT_FIELD_FAILURE';

// GET ALL
export const GET_ALL_SUBJECT_FIELDS = 'GET_ALL_SUBJECT_FIELDS';
export const GET_ALL_SUBJECT_FIELDS_SUCCESS = 'GET_ALL_SUBJECT_FIELDS_SUCCESS';
export const GET_ALL_SUBJECT_FIELDS_FAILURE = 'GET_ALL_SUBJECT_FIELDS_FAILURE';
