// UPDATE
export const UPDATE_WEEKLY_REPORT_CONFIG = 'UPDATE_WEEKLY_REPORT_CONFIG';
export const UPDATE_WEEKLY_REPORT_CONFIG_FAILURE = 'UPDATE_WEEKLY_REPORT_CONFIG_FAILURE';
export const UPDATE_WEEKLY_REPORT_CONFIG_SUCCESS = 'UPDATE_WEEKLY_REPORT_CONFIG_SUCCESS';

// GET
export const GET_WEEKLY_REPORT_CONFIG = 'GET_WEEKLY_REPORT_CONFIG';
export const GET_WEEKLY_REPORT_CONFIG_FAILURE = 'GET_WEEKLY_REPORT_CONFIG_FAILURE';
export const GET_WEEKLY_REPORT_CONFIG_SUCCESS = 'GET_WEEKLY_REPORT_CONFIG_SUCCESS';

// GET BY ID
export const GET_WEEKLY_REPORT_CONFIG_BY_ID = 'GET_WEEKLY_REPORT_CONFIG_BY_ID';
export const GET_WEEKLY_REPORT_CONFIG_BY_ID_FAILURE = 'GET_WEEKLY_REPORT_CONFIG_BY_ID_FAILURE';
export const GET_WEEKLY_REPORT_CONFIG_BY_ID_SUCCESS = 'GET_WEEKLY_REPORT_CONFIG_BY_ID_SUCCESS';
