// ADD
export const ADD_STAFFDOCUMENT = 'ADD_STAFFDOCUMENT';
export const ADD_STAFFDOCUMENT_SUCCESS = 'ADD_STAFFDOCUMENT_SUCCESS';
export const ADD_STAFFDOCUMENT_FAILURE = 'ADD_STAFFDOCUMENT_FAILURE';

// DELETE
export const DELETE_STAFFDOCUMENT = 'DELETE_STAFFDOCUMENT';
export const DELETE_STAFFDOCUMENT_SUCCESS = 'DELETE_STAFFDOCUMENT_SUCCESS';
export const DELETE_STAFFDOCUMENT_FAILURE = 'DELETE_STAFFDOCUMENT_FAILURE';

