// UPDATE
export const UPDATE_STAFFCONTRACT = 'UPDATE_STAFFCONTRACT';
export const UPDATE_STAFFCONTRACT_SUCCESS = 'UPDATE_STAFFCONTRACT_SUCCESS';
export const UPDATE_STAFFCONTRACT_FAILURE = 'UPDATE_STAFFCONTRACT_FAILURE';

// GET ALL BY CONTRACT TYPE
export const GET_ALL_STAFFCONTRACT_BY_CONTRACTTYPE = 'GET_ALL_STAFFCONTRACT_BY_CONTRACTTYPE';
export const GET_ALL_STAFFCONTRACT_BY_CONTRACTTYPE_SUCCESS = 'GET_ALL_STAFFCONTRACT_BY_CONTRACTTYPE_SUCCESS';
export const GET_ALL_STAFFCONTRACT_BY_CONTRACTTYPE_FAILURE = 'GET_ALL_STAFFCONTRACT_BY_CONTRACTTYPE_FAILURE';

// GET ALL BY LEGAL CATEGORY TYPE
export const GET_ALL_STAFFCONTRACT_BY_LEGALCATEGORYTYPE = 'GET_ALL_STAFFCONTRACT_BY_LEGALCATEGORYTYPE';
export const GET_ALL_STAFFCONTRACT_BY_LEGALCATEGORYTYPE_SUCCESS = 'GET_ALL_STAFFCONTRACT_BY_LEGALCATEGORYTYPE_SUCCESS';
export const GET_ALL_STAFFCONTRACT_BY_LEGALCATEGORYTYPE_FAILURE = 'GET_ALL_STAFFCONTRACT_BY_LEGALCATEGORYTYPE_FAILURE';

// GET ALL BY CONTRACT MODEL
export const GET_ALL_STAFFCONTRACT_BY_CONTRACTMODEL = 'GET_ALL_STAFFCONTRACT_BY_CONTRACTMODEL';
export const GET_ALL_STAFFCONTRACT_BY_CONTRACTMODEL_SUCCESS = 'GET_ALL_STAFFCONTRACT_BY_CONTRACTMODEL_SUCCESS';
export const GET_ALL_STAFFCONTRACT_BY_CONTRACTMODEL_FAILURE = 'GET_ALL_STAFFCONTRACT_BY_CONTRACTMODEL_FAILURE';
