// GET TRAVEL REQUESTS
export const GET_TRAVEL_REQUESTS = 'GET_TRAVEL_REQUESTS';
export const GET_TRAVEL_REQUESTS_FAILURE = 'GET_TRAVEL_REQUESTS_FAILURE';
export const GET_TRAVEL_REQUESTS_SUCCESS = 'GET_TRAVEL_REQUESTS_SUCCESS';

// ADD TRAVEL REQUEST
export const ADD_TRAVEL_REQUEST = 'ADD_TRAVEL_REQUEST';
export const ADD_TRAVEL_REQUEST_FAILURE = 'ADD_TRAVEL_REQUEST_FAILURE';
export const ADD_TRAVEL_REQUEST_SUCCESS = 'ADD_TRAVEL_REQUEST_SUCCESS';

// UPDATE TRAVEL REQUEST
export const UPDATE_TRAVEL_REQUEST = 'UPDATE_TRAVEL_REQUEST';
export const UPDATE_TRAVEL_REQUEST_FAILURE = 'UPDATE_TRAVEL_REQUEST_FAILURE';
export const UPDATE_TRAVEL_REQUEST_SUCCESS = 'UPDATE_TRAVEL_REQUEST_SUCCESS';

// CHANGE STATUS TRAVEL REQUEST
export const CHANGE_STATUS_TRAVEL_REQUEST = 'CHANGE_STATUS_TRAVEL_REQUEST';
export const CHANGE_STATUS_TRAVEL_REQUEST_FAILURE = 'CHANGE_STATUS_TRAVEL_REQUEST_FAILURE';
export const CHANGE_STATUS_TRAVEL_REQUEST_SUCCESS = 'CHANGE_STATUS_TRAVEL_REQUEST_SUCCESS';

// GET COUNTRIES
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_FAILURE = 'GET_COUNTRIES_FAILURE';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';

// GET TRAVEL REQUESTS REPORT
export const EXPORT_TRAVEL_REQUESTS = 'EXPORT_TRAVEL_REQUESTS';
export const EXPORT_TRAVEL_REQUESTS_FAILURE = 'EXPORT_TRAVEL_REQUESTS_FAILURE';
export const EXPORT_TRAVEL_REQUESTS_SUCCESS = 'EXPORT_TRAVEL_REQUESTS_SUCCESS';

// APPROVE TRAVEL REQUEST
export const APPROVE_TRAVEL_REQUEST = 'APPROVE_TRAVEL_REQUEST';
export const APPROVE_TRAVEL_REQUEST_FAILURE = 'APPROVE_TRAVEL_REQUEST_FAILURE';
export const APPROVE_TRAVEL_REQUEST_SUCCESS = 'APPROVE_TRAVEL_REQUEST_SUCCESS';

// DOWNLOAD DOCUMENTS OF TRAVEL REQUEST
export const DOWNLOAD_DOCUMENTS_OF_TRAVEL_REQUEST = 'DOWNLOAD_DOCUMENTS_OF_TRAVEL_REQUEST';
export const DOWNLOAD_DOCUMENTS_OF_TRAVEL_REQUEST_FAILURE = 'DOWNLOAD_DOCUMENTS_OF_TRAVEL_REQUEST_FAILURE';
export const DOWNLOAD_DOCUMENTS_OF_TRAVEL_REQUEST_SUCCESS = 'DOWNLOAD_DOCUMENTS_OF_TRAVEL_REQUEST_SUCCESS';
