// ADD
export const ADD_ABSENCETYPE = 'ADD_ABSENCETYPE';
export const ADD_ABSENCETYPE_SUCCESS = 'ADD_ABSENCETYPE_SUCCESS';
export const ADD_ABSENCETYPE_FAILURE = 'ADD_ABSENCETYPE_FAILURE';

// UPDATE
export const UPDATE_ABSENCETYPE = 'UPDATE_ABSENCETYPE';
export const UPDATE_ABSENCETYPE_SUCCESS = 'UPDATE_ABSENCETYPE_SUCCESS';
export const UPDATE_ABSENCETYPE_FAILURE = 'UPDATE_ABSENCETYPE_FAILURE';

// DELETE
export const DELETE_ABSENCETYPE = 'DELETE_ABSENCETYPE';
export const DELETE_ABSENCETYPE_SUCCESS = 'DELETE_ABSENCETYPE_SUCCESS';
export const DELETE_ABSENCETYPE_FAILURE = 'DELETE_ABSENCETYPE_FAILURE';

// GET ALL
export const GET_ALL_ABSENCETYPES = 'GET_ALL_ABSENCETYPES';
export const GET_ALL_ABSENCETYPES_SUCCESS = 'GET_ALL_ABSENCETYPES_SUCCESS';
export const GET_ALL_ABSENCETYPES_FAILURE = 'GET_ALL_ABSENCETYPES_FAILURE';

// GET ALL BY STATE
export const GET_ALL_ABSENCETYPES_BY_STATE = 'GET_ALL_ABSENCETYPES_BY_STATE';
export const GET_ALL_ABSENCETYPES_BY_STATE_SUCCESS = 'GET_ALL_ABSENCETYPES_BY_STATE_SUCCESS';
export const GET_ALL_ABSENCETYPES_BY_STATE_FAILURE = 'GET_ALL_ABSENCETYPES_BY_STATE_FAILURE';
