// UPDATE
export const UPDATE_OPERATION_ASSIGNMENT = 'UPDATE_OPERATION_ASSIGNMENT';
export const UPDATE_OPERATION_ASSIGNMENT_FAILURE = 'UPDATE_OPERATION_ASSIGNMENT_FAILURE';
export const UPDATE_OPERATION_ASSIGNMENT_SUCCESS = 'UPDATE_OPERATION_ASSIGNMENT_SUCCESS';

// GET TREE DATA
export const GET_TREE_DATA = 'GET_TREE_DATA';
export const GET_TREE_DATA_FAILURE = 'GET_TREE_DATA_FAILURE';
export const GET_TREE_DATA_SUCCESS = 'GET_TREE_DATA_SUCCESS';

// GET TREE DATA
export const GET_ELIGIBLE_STAFF = 'GET_ELIGIBLE_STAFF_DATA';
export const GET_ELIGIBLE_STAFF_FAILURE = 'GET_ELIGIBLE_STAFF_FAILURE';
export const GET_ELIGIBLE_STAFF_SUCCESS = 'GET_ELIGIBLE_STAFF_SUCCESS';

// GET STAFF ASSIGNED BY OPERATION
export const GET_STAFF_ASSIGNED_BY_OPERATION = 'GET_STAFF_ASSIGNED_BY_OPERATION';
export const GET_STAFF_ASSIGNED_BY_OPERATION_FAILURE = 'GET_STAFF_ASSIGNED_BY_OPERATION_FAILURE';
export const GET_STAFF_ASSIGNED_BY_OPERATION_SUCCESS = 'GET_STAFF_ASSIGNED_BY_OPERATION_SUCCESS';

// FILTER SATFF BY EMAIL
export const FILTER_STAFF_BY_EMAIL = 'FILTER_STAFF_BY_EMAIL';
export const FILTER_STAFF_BY_EMAIL_FAILURE = 'FILTER_STAFF_BY_EMAIL_FAILURE';
export const FILTER_STAFF_BY_EMAIL_SUCCESS = 'FILTER_STAFF_BY_EMAIL_SUCCESS';

// GET CUSTOMER CONTRACTS BY EMPLOYEE
export const GET_CUSTOMER_CONTRACTS_BY_EMPLOYEE = 'GET_CUSTOMER_CONTRACTS_BY_EMPLOYEE';
export const GET_CUSTOMER_CONTRACTS_BY_EMPLOYEE_FAILURE = 'GET_CUSTOMER_CONTRACTS_BY_EMPLOYEE_FAILURE';
export const GET_CUSTOMER_CONTRACTS_BY_EMPLOYEE_SUCCESS = 'GET_CUSTOMER_CONTRACTS_BY_EMPLOYEE_SUCCESS';

// GET CUSTOMER CONTRACTS BY COMPANY EMAIL
export const GET_CUSTOMER_CONTRACTS_BY_COMPANY_EMAIL = 'GET_CUSTOMER_CONTRACTS_BY_COMPANY_EMAIL';
export const GET_CUSTOMER_CONTRACTS_BY_COMPANY_EMAIL_FAILURE = 'GET_CUSTOMER_CONTRACTS_BY_COMPANY_EMAIL_FAILURE';
export const GET_CUSTOMER_CONTRACTS_BY_COMPANY_EMAIL_SUCCESS = 'GET_CUSTOMER_CONTRACTS_BY_COMPANY_EMAIL_SUCCESS';

// GET OPERATIONS BY EMPLOYEE AND CUSTOMER
export const GET_OPERATIONS_BY_EMPLOYEE_AND_CUSTOMER = 'GET_OPERATIONS_BY_EMPLOYEE_AND_CUSTOMER';
export const GET_OPERATIONS_BY_EMPLOYEE_AND_CUSTOMER_FAILURE = 'GET_OPERATIONS_BY_EMPLOYEE_AND_CUSTOMER_FAILURE';
export const GET_OPERATIONS_BY_EMPLOYEE_AND_CUSTOMER_SUCCESS = 'GET_OPERATIONS_BY_EMPLOYEE_AND_CUSTOMER_SUCCESS';

// EXPORT STAFF ASSIGNMENT HISTORY
export const EXPORT_STAFF_ASSIGNMENT = 'EXPORT_STAFF_ASSIGNMENT';
export const EXPORT_STAFF_ASSIGNMENT_FAILURE = 'EXPORT_STAFF_ASSIGNMENT_FAILURE';
export const EXPORT_STAFF_ASSIGNMENT_SUCCESS = 'EXPORT_STAFF_ASSIGNMENT_SUCCESS';
