// ADD
export const ADD_CONTRACTTYPE = 'ADD_CONTRACTTYPE';
export const ADD_CONTRACTTYPE_SUCCESS = 'ADD_CONTRACTTYPE_SUCCESS';
export const ADD_CONTRACTTYPE_FAILURE = 'ADD_CONTRACTTYPE_FAILURE';

// UPDATE
export const UPDATE_CONTRACTTYPE = 'UPDATE_CONTRACTTYPE';
export const UPDATE_CONTRACTTYPE_SUCCESS = 'UPDATE_CONTRACTTYPE_SUCCESS';
export const UPDATE_CONTRACTTYPE_FAILURE = 'UPDATE_CONTRACTTYPE_FAILURE';

// DELETE
export const DELETE_CONTRACTTYPE = 'DELETE_CONTRACTTYPE';
export const DELETE_CONTRACTTYPE_SUCCESS = 'DELETE_CONTRACTTYPE_SUCCESS';
export const DELETE_CONTRACTTYPE_FAILURE = 'DELETE_CONTRACTTYPE_FAILURE';

// GET ALL
export const GET_ALL_CONTRACTTYPES = 'GET_ALL_CONTRACTTYPES';
export const GET_ALL_CONTRACTTYPES_SUCCESS = 'GET_ALL_CONTRACTTYPES_SUCCESS';
export const GET_ALL_CONTRACTTYPES_FAILURE = 'GET_ALL_CONTRACTTYPES_FAILURE';

// GET ALL BY STATE
export const GET_ALL_CONTRACTTYPES_BY_STATE = 'GET_ALL_CONTRACTTYPES_BY_STATE';
export const GET_ALL_CONTRACTTYPES_BY_STATE_SUCCESS = 'GET_ALL_CONTRACTTYPES_BY_STATE_SUCCESS';
export const GET_ALL_CONTRACTTYPES_BY_STATE_FAILURE = 'GET_ALL_CONTRACTTYPES_BY_STATE_FAILURE';
