
// SAVE VOUCHER TYPE
export const ADD_VOUCHER_TYPE = 'ADD_VOUCHER_TYPE';
export const ADD_VOUCHER_TYPE_FAILURE = 'ADD_VOUCHER_TYPE_FAILURE';
export const ADD_VOUCHER_TYPE_SUCCESS = 'ADD_VOUCHER_TYPE_SUCCESS';

// UPDATE VOUCHER TYPE
export const UPDATE_VOUCHER_TYPE = 'UPDATE_VOUCHER_TYPE';
export const UPDATE_VOUCHER_TYPE_FAILURE = 'UPDATE_VOUCHER_TYPE_FAILURE';
export const UPDATE_VOUCHER_TYPE_SUCCESS = 'UPDATE_VOUCHER_TYPE_SUCCESS';

// DELETE VOUCHER TYPE
export const DELETE_VOUCHER_TYPE = 'DELETE_VOUCHER_TYPE';
export const DELETE_VOUCHER_TYPE_FAILURE = 'DELETE_VOUCHER_TYPE_FAILURE';
export const DELETE_VOUCHER_TYPE_SUCCESS = 'DELETE_VOUCHER_TYPE_SUCCESS';

// GET ALL VOUCHER TYPES
export const GET_ALL_VOUCHER_TYPES = 'GET_ALL_VOUCHER_TYPES';
export const GET_ALL_VOUCHER_TYPES_FAILURE = 'GET_ALL_VOUCHER_TYPES_FAILURE';
export const GET_ALL_VOUCHER_TYPES_SUCCESS = 'GET_ALL_VOUCHER_TYPES_SUCCESS';
