// ADD
export const ADD_SECTORCOMPANY = 'ADD_SECTORCOMPANY';
export const ADD_SECTORCOMPANY_SUCCESS = 'ADD_SECTORCOMPANY_SUCCESS';
export const ADD_SECTORCOMPANY_FAILURE = 'ADD_SECTORCOMPANY_FAILURE';

// UPDATE
export const UPDATE_SECTORCOMPANY = 'UPDATE_SECTORCOMPANY';
export const UPDATE_SECTORCOMPANY_SUCCESS = 'UPDATE_SECTORCOMPANY_SUCCESS';
export const UPDATE_SECTORCOMPANY_FAILURE = 'UPDATE_SECTORCOMPANY_FAILURE';

// DELETE
export const DELETE_SECTORCOMPANY = 'DELETE_SECTORCOMPANY';
export const DELETE_SECTORCOMPANY_SUCCESS = 'DELETE_SECTORCOMPANY_SUCCESS';
export const DELETE_SECTORCOMPANY_FAILURE = 'DELETE_SECTORCOMPANY_FAILURE';

// DELETE
export const DELETECONFIRMATION_SECTORCOMPANY = 'DELETECONFIRMATION_SECTORCOMPANY';
export const DELETECONFIRMATION_SECTORCOMPANY_SUCCESS = 'DELETECONFIRMATION_SECTORCOMPANY_SUCCESS';
export const DELETECONFIRMATION_SECTORCOMPANY_FAILURE = 'DELETECONFIRMATION_SECTORCOMPANY_FAILURE';

// GET ALL
export const GET_ALL_SECTORCOMPANYS = 'GET_ALL_SECTORCOMPANYS';
export const GET_ALL_SECTORCOMPANYS_SUCCESS = 'GET_ALL_SECTORCOMPANYS_SUCCESS';
export const GET_ALL_SECTORCOMPANYS_FAILURE = 'GET_ALL_SECTORCOMPANYS_FAILURE';

// GET ALL
export const GET_ALL_CHILDSECTORCOMPANYS = 'GET_ALL_CHILDSECTORCOMPANYS';
export const GET_ALL_CHILDSECTORCOMPANYS_SUCCESS = 'GET_ALL_CHILDSECTORCOMPANYS_SUCCESS';
export const GET_ALL_CHILDSECTORCOMPANYS_FAILURE = 'GET_ALL_CHILDSECTORCOMPANYS_FAILURE';

// GET ALL
export const GET_ALL_SUBCHILDSECTORCOMPANYS = 'GET_ALL_SUBCHILDSECTORCOMPANYS';
export const GET_ALL_SUBCHILDSECTORCOMPANYS_SUCCESS = 'GET_ALL_SUBCHILDSECTORCOMPANYS_SUCCESS';
export const GET_ALL_SUBCHILDSECTORCOMPANYS_FAILURE = 'GET_ALL_SUBCHILDSECTORCOMPANYS_FAILURE';

// GET ALL PRIMARY SECTORS
export const GET_ALL_PRIMARYSECTORCOMPANYS = 'GET_ALL_PRIMARYSECTORCOMPANYS';
export const GET_ALL_PRIMARYSECTORCOMPANYS_SUCCESS = 'GET_ALL_PRIMARYSECTORCOMPANYS_SUCCESS';
export const GET_ALL_PRIMARYSECTORCOMPANYS_FAILURE = 'GET_ALL_PRIMARYSECTORCOMPANYS_FAILURE';
