// ADD
export const ADD_COMMERCIALSERVICETYPE = 'ADD_COMMERCIALSERVICETYPE';
export const ADD_COMMERCIALSERVICETYPE_SUCCESS = 'ADD_COMMERCIALSERVICETYPE_SUCCESS';
export const ADD_COMMERCIALSERVICETYPE_FAILURE = 'ADD_COMMERCIALSERVICETYPE_FAILURE';

// UPDATE
export const UPDATE_COMMERCIALSERVICETYPE = 'UPDATE_COMMERCIALSERVICETYPE';
export const UPDATE_COMMERCIALSERVICETYPE_SUCCESS = 'UPDATE_COMMERCIALSERVICETYPE_SUCCESS';
export const UPDATE_COMMERCIALSERVICETYPE_FAILURE = 'UPDATE_COMMERCIALSERVICETYPE_FAILURE';

// DELETE
export const DELETE_COMMERCIALSERVICETYPE = 'DELETE_COMMERCIALSERVICETYPE';
export const DELETE_COMMERCIALSERVICETYPE_SUCCESS = 'DELETE_COMMERCIALSERVICETYPE_SUCCESS';
export const DELETE_COMMERCIALSERVICETYPE_FAILURE = 'DELETE_COMMERCIALSERVICETYPE_FAILURE';

// GET ALL
export const GET_ALL_COMMERCIALSERVICETYPES = 'GET_ALL_COMMERCIALSERVICETYPES';
export const GET_ALL_COMMERCIALSERVICETYPES_SUCCESS = 'GET_ALL_COMMERCIALSERVICETYPES_SUCCESS';
export const GET_ALL_COMMERCIALSERVICETYPES_FAILURE = 'GET_ALL_COMMERCIALSERVICETYPES_FAILURE';


// UPDATE
export const UPDATE_DELETE_COMMERCIALSERVICETYPE = 'UPDATE_DELETE_COMMERCIALSERVICETYPE';
export const UPDATE_DELETE_COMMERCIALSERVICETYPE_SUCCESS = 'UPDATE_DELETE_COMMERCIALSERVICETYPE_SUCCESS';
export const UPDATE_DELETE_COMMERCIALSERVICETYPE_FAILURE = 'UPDATE_DELETE_COMMERCIALSERVICETYPE_FAILURE';