// ADD
export const ADD_ADMINISTRATIVESTRUCTURELEVEL = 'ADD_ADMINISTRATIVESTRUCTURELEVEL';
export const ADD_ADMINISTRATIVESTRUCTURELEVEL_SUCCESS = 'ADD_ADMINISTRATIVESTRUCTURELEVEL_SUCCESS';
export const ADD_ADMINISTRATIVESTRUCTURELEVEL_FAILURE = 'ADD_ADMINISTRATIVESTRUCTURELEVEL_FAILURE';

// UPDATE
export const UPDATE_ADMINISTRATIVESTRUCTURELEVEL = 'UPDATE_ADMINISTRATIVESTRUCTURELEVEL';
export const UPDATE_ADMINISTRATIVESTRUCTURELEVEL_SUCCESS = 'UPDATE_ADMINISTRATIVESTRUCTURELEVEL_SUCCESS';
export const UPDATE_ADMINISTRATIVESTRUCTURELEVEL_FAILURE = 'UPDATE_ADMINISTRATIVESTRUCTURELEVEL_FAILURE';

// DELETE
export const DELETE_ADMINISTRATIVESTRUCTURELEVEL = 'DELETE_ADMINISTRATIVESTRUCTURELEVEL';
export const DELETE_ADMINISTRATIVESTRUCTURELEVEL_SUCCESS = 'DELETE_ADMINISTRATIVESTRUCTURELEVEL_SUCCESS';
export const DELETE_ADMINISTRATIVESTRUCTURELEVEL_FAILURE = 'DELETE_ADMINISTRATIVESTRUCTURELEVEL_FAILURE';

// GET ALL
export const GET_ALL_ADMINISTRATIVESTRUCTURELEVELS = 'GET_ALL_ADMINISTRATIVESTRUCTURELEVELS';
export const GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_SUCCESS = 'GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_SUCCESS';
export const GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_FAILURE = 'GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_FAILURE';

// GET ALL BY TYPE
export const GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_BY_TYPE = 'GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_BY_TYPE';
export const GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_BY_TYPE_SUCCESS = 'GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_BY_TYPE_SUCCESS';
export const GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_BY_TYPE_FAILURE = 'GET_ALL_ADMINISTRATIVESTRUCTURELEVELS_BY_TYPE_FAILURE';
