// GET EXPENSES
export const GET_EXPENSES = 'GET_EXPENSES';
export const GET_EXPENSES_FAILURE = 'GET_EXPENSES_FAILURE';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';

// SAVE EXPENSE
export const SAVE_EXPENSE = 'SAVE_EXPENSE';
export const SAVE_EXPENSE_FAILURE = 'SAVE_EXPENSE_FAILURE';
export const SAVE_EXPENSE_SUCCESS = 'SAVE_EXPENSE_SUCCESS';

// SAVE EXPENSE WITH FILE
export const SAVE_EXPENSE_WITH_FILE = 'SAVE_EXPENSE_WITH_FILE';
export const SAVE_EXPENSE_WITH_FILE_FAILURE = 'SAVE_EXPENSE_WITH_FILE_FAILURE';
export const SAVE_EXPENSE_WITH_FILE_SUCCESS = 'SAVE_EXPENSE_WITH_FILE_SUCCESS';

// CHANGE STATUS EXPENSE
export const CHANGE_STATUS_EXPENSE = 'CHANGE_STATUS_EXPENSE';
export const CHANGE_STATUS_EXPENSE_FAILURE = 'CHANGE_STATUS_EXPENSE_FAILURE';
export const CHANGE_STATUS_EXPENSE_SUCCESS = 'CHANGE_STATUS_EXPENSE_SUCCESS';

// GET EXPENSES REPORT
export const EXPORT_EXPENSES = 'EXPORT_EXPENSES';
export const EXPORT_EXPENSES_FAILURE = 'EXPORT_EXPENSES_FAILURE';
export const EXPORT_EXPENSES_SUCCESS = 'EXPORT_EXPENSES_SUCCESS';

// DOWNLOAD DOCUMENTS OF EXPENSE
export const DOWNLOAD_DOCUMENT_OF_EXPENSE = 'DOWNLOAD_DOCUMENT_OF_EXPENSE';
export const DOWNLOAD_DOCUMENT_OF_EXPENSE_FAILURE = 'DOWNLOAD_DOCUMENT_OF_EXPENSE_FAILURE';
export const DOWNLOAD_DOCUMENT_OF_EXPENSE_SUCCESS = 'DOWNLOAD_DOCUMENT_OF_EXPENSE_SUCCESS';
