// ADD
export const ADD_ACTION = 'ADD_ACTION';
export const ADD_ACTION_SUCCESS = 'ADD_ACTION_SUCCESS';
export const ADD_ACTION_FAILURE = 'ADD_ACTION_FAILURE';

// UPDATE
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const UPDATE_ACTION_SUCCESS = 'UPDATE_ACTION_SUCCESS';
export const UPDATE_ACTION_FAILURE = 'UPDATE_ACTION_FAILURE';

// DELETE
export const DELETE_ACTION = 'DELETE_ACTION';
export const DELETE_ACTION_SUCCESS = 'DELETE_ACTION_SUCCESS';
export const DELETE_ACTION_FAILURE = 'DELETE_ACTION_FAILURE';

// GET ALL
export const GET_ALL_ACTIONS = 'GET_ALL_ACTIONS';
export const GET_ALL_ACTIONS_SUCCESS = 'GET_ALL_ACTIONS_SUCCESS';
export const GET_ALL_ACTIONS_FAILURE = 'GET_ALL_ACTIONS_FAILURE';
