// ADD
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS';
export const ADD_COUNTRY_FAILURE = 'ADD_COUNTRY_FAILURE';

// UPDATE
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const UPDATE_COUNTRY_SUCCESS = 'UPDATE_COUNTRY_SUCCESS';
export const UPDATE_COUNTRY_FAILURE = 'UPDATE_COUNTRY_FAILURE';

// DELETE
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS';
export const DELETE_COUNTRY_FAILURE = 'DELETE_COUNTRY_FAILURE';

// GET ALL
export const GET_ALL_COUNTRYS = 'GET_ALL_COUNTRYS';
export const GET_ALL_COUNTRYS_SUCCESS = 'GET_ALL_COUNTRYS_SUCCESS';
export const GET_ALL_COUNTRYS_FAILURE = 'GET_ALL_COUNTRYS_FAILURE';
