// ADD BUSINESS EXPENSE TYPE
export const ADD_BUSINESS_EXPENSE_TYPE = 'ADD_BUSINESS_EXPENSE_TYPE';
export const ADD_BUSINESS_EXPENSE_TYPE_FAILURE = 'ADD_BUSINESS_EXPENSE_TYPE_FAILURE';
export const ADD_BUSINESS_EXPENSE_TYPE_SUCCESS = 'ADD_BUSINESS_EXPENSE_TYPE_SUCCESS';

// UPDATE BUSINESS EXPENSE TYPE
export const UPDATE_BUSINESS_EXPENSE_TYPE = 'UPDATE_BUSINESS_EXPENSE_TYPE';
export const UPDATE_BUSINESS_EXPENSE_TYPE_FAILURE = 'UPDATE_BUSINESS_EXPENSE_TYPE_FAILURE';
export const UPDATE_BUSINESS_EXPENSE_TYPE_SUCCESS = 'UPDATE_BUSINESS_EXPENSE_TYPE_SUCCESS';

// DELETE BUSINESS EXPENSE TYPE
export const DELETE_BUSINESS_EXPENSE_TYPE = 'DELETE_BUSINESS_EXPENSE_TYPE';
export const DELETE_BUSINESS_EXPENSE_TYPE_FAILURE = 'DELETE_BUSINESS_EXPENSE_TYPE_FAILURE';
export const DELETE_BUSINESS_EXPENSE_TYPE_SUCCESS = 'DELETE_BUSINESS_EXPENSE_TYPE_SUCCESS';

// GET BUSINESS EXPENSES TYPES
export const GET_BUSINESS_EXPENSES_TYPES = 'GET_BUSINESS_EXPENSES_TYPES';
export const GET_BUSINESS_EXPENSES_TYPES_FAILURE = 'GET_BUSINESS_EXPENSES_TYPES_FAILURE';
export const GET_BUSINESS_EXPENSES_TYPES_SUCCESS = 'GET_BUSINESS_EXPENSES_TYPES_SUCCESS';

//---------------------------------------------------------------------------------------------

// ADD BUSINESS EXPENSE SUBTYPE
export const ADD_BUSINESS_EXPENSE_SUBTYPE = 'ADD_BUSINESS_EXPENSE_SUBTYPE';
export const ADD_BUSINESS_EXPENSE_SUBTYPE_FAILURE = 'ADD_BUSINESS_EXPENSE_SUBTYPE_FAILURE';
export const ADD_BUSINESS_EXPENSE_SUBTYPE_SUCCESS = 'ADD_BUSINESS_EXPENSE_SUBTYPE_SUCCESS';

// UPDATE BUSINESS EXPENSE SUBTYPE
export const UPDATE_BUSINESS_EXPENSE_SUBTYPE = 'UPDATE_BUSINESS_EXPENSE_SUBTYPE';
export const UPDATE_BUSINESS_EXPENSE_SUBTYPE_FAILURE = 'UPDATE_BUSINESS_EXPENSE_SUBTYPE_FAILURE';
export const UPDATE_BUSINESS_EXPENSE_SUBTYPE_SUCCESS = 'UPDATE_BUSINESS_EXPENSE_SUBTYPE_SUCCESS';

// DELETE BUSINESS EXPENSE SUBTYPE
export const DELETE_BUSINESS_EXPENSE_SUBTYPE = 'DELETE_BUSINESS_EXPENSE_SUBTYPE';
export const DELETE_BUSINESS_EXPENSE_SUBTYPE_FAILURE = 'DELETE_BUSINESS_EXPENSE_SUBTYPE_FAILURE';
export const DELETE_BUSINESS_EXPENSE_SUBTYPE_SUCCESS = 'DELETE_BUSINESS_EXPENSE_SUBTYPE_SUCCESS';
