// ADD
export const ADD_SELECTIONTYPEEVALUATION = 'ADD_SELECTIONTYPEEVALUATION';
export const ADD_SELECTIONTYPEEVALUATION_SUCCESS = 'ADD_SELECTIONTYPEEVALUATION_SUCCESS';
export const ADD_SELECTIONTYPEEVALUATION_FAILURE = 'ADD_SELECTIONTYPEEVALUATION_FAILURE';

// UPDATE
export const UPDATE_SELECTIONTYPEEVALUATION = 'UPDATE_SELECTIONTYPEEVALUATION';
export const UPDATE_SELECTIONTYPEEVALUATION_SUCCESS = 'UPDATE_SELECTIONTYPEEVALUATION_SUCCESS';
export const UPDATE_SELECTIONTYPEEVALUATION_FAILURE = 'UPDATE_SELECTIONTYPEEVALUATION_FAILURE';

// DELETE
export const DELETE_SELECTIONTYPEEVALUATION = 'DELETE_SELECTIONTYPEEVALUATION';
export const DELETE_SELECTIONTYPEEVALUATION_SUCCESS = 'DELETE_SELECTIONTYPEEVALUATION_SUCCESS';
export const DELETE_SELECTIONTYPEEVALUATION_FAILURE = 'DELETE_SELECTIONTYPEEVALUATION_FAILURE';

// GET ALL
export const GET_ALL_SELECTIONTYPEEVALUATIONS = 'GET_ALL_SELECTIONTYPEEVALUATIONS';
export const GET_ALL_SELECTIONTYPEEVALUATIONS_SUCCESS = 'GET_ALL_SELECTIONTYPEEVALUATIONS_SUCCESS';
export const GET_ALL_SELECTIONTYPEEVALUATIONS_FAILURE = 'GET_ALL_SELECTIONTYPEEVALUATIONS_FAILURE';

// GET ALL BY TYPE
export const GET_ALL_SELECTIONTYPEEVALUATIONS_BY_TYPE = 'GET_ALL_SELECTIONTYPEEVALUATIONS_BY_TYPE';
export const GET_ALL_SELECTIONTYPEEVALUATIONS_BY_TYPE_SUCCESS = 'GET_ALL_SELECTIONTYPEEVALUATIONS_BY_TYPE_SUCCESS';
export const GET_ALL_SELECTIONTYPEEVALUATIONS_BY_TYPE_FAILURE = 'GET_ALL_SELECTIONTYPEEVALUATIONS_BY_TYPE_FAILURE';
