// SAVE
export const ADD_ASSIGNMENT_TYPE = 'ADD_ASSIGNMENT_TYPE';
export const ADD_ASSIGNMENT_TYPE_FAILURE = 'ADD_ASSIGNMENT_TYPE_FAILURE';
export const ADD_ASSIGNMENT_TYPE_SUCCESS = 'ADD_ASSIGNMENT_TYPE_SUCCESS';

// UPDATE
export const UPDATE_ASSIGNMENT_TYPE = 'UPDATE_ASSIGNMENT_TYPE';
export const UPDATE_ASSIGNMENT_TYPE_FAILURE = 'UPDATE_ASSIGNMENT_TYPE_FAILURE';
export const UPDATE_ASSIGNMENT_TYPE_SUCCESS = 'UPDATE_ASSIGNMENT_TYPE_SUCCESS';

// DELETE
export const DELETE_ASSIGNMENT_TYPE = 'DELETE_ASSIGNMENT_TYPE';
export const DELETE_ASSIGNMENT_TYPE_FAILURE = 'DELETE_ASSIGNMENT_TYPE_FAILURE';
export const DELETE_ASSIGNMENT_TYPE_SUCCESS = 'DELETE_ASSIGNMENT_TYPE_SUCCESS';

// GET ALL
export const GET_ALL_ASSIGNMENT_TYPES = 'GET_ALL_ASSIGNMENT_TYPES';
export const GET_ALL_ASSIGNMENT_TYPES_FAILURE = 'GET_ALL_ASSIGNMENT_TYPES_FAILURE';
export const GET_ALL_ASSIGNMENT_TYPES_SUCCESS = 'GET_ALL_ASSIGNMENT_TYPES_SUCCESS';
