// ADD
export const ADD_ABSENCEREQUEST = 'ADD_ABSENCEREQUEST';
export const ADD_ABSENCEREQUEST_SUCCESS = 'ADD_ABSENCEREQUEST_SUCCESS';
export const ADD_ABSENCEREQUEST_FAILURE = 'ADD_ABSENCEREQUEST_FAILURE';

// UPDATE request
export const UPDATE_ABSENCEREQUEST = 'UPDATE_ABSENCEREQUEST';
export const UPDATE_ABSENCEREQUEST_SUCCESS = 'UPDATE_ABSENCEREQUEST_SUCCESS';
export const UPDATE_ABSENCEREQUEST_FAILURE = 'UPDATE_ABSENCEREQUEST_FAILURE';
// UPDATE
export const UPDATE_ABSENCECONSULT = 'UPDATE_ABSENCECONSULT';
export const UPDATE_ABSENCECONSULT_SUCCESS = 'UPDATE_ABSENCEREQUEST_SUCCESS';
export const UPDATE_ABSENCECONSULT_FAILURE = 'UPDATE_ABSENCEREQUEST_FAILURE';

// DELETE
export const DELETE_ABSENCEREQUEST = 'DELETE_ABSENCEREQUEST';
export const DELETE_ABSENCEREQUEST_SUCCESS = 'DELETE_ABSENCEREQUEST_SUCCESS';
export const DELETE_ABSENCEREQUEST_FAILURE = 'DELETE_ABSENCEREQUEST_FAILURE';

// GET ALL
export const GET_ALL_ABSENCEREQUESTS = 'GET_ALL_ABSENCEREQUESTS';
export const GET_ALL_ABSENCEREQUESTS_SUCCESS = 'GET_ALL_ABSENCEREQUESTS_SUCCESS';
export const GET_ALL_ABSENCEREQUESTS_FAILURE = 'GET_ALL_ABSENCEREQUESTS_FAILURE';

// GET ALL BY ABSENCE TYPE
export const GET_ALL_ABSENCEREQUEST_BY_ABSENCETYPE = 'GET_ALL_ABSENCEREQUEST_BY_ABSENCETYPE';
export const GET_ALL_ABSENCEREQUEST_BY_ABSENCETYPE_SUCCESS = 'GET_ALL_ABSENCEREQUEST_BY_ABSENCETYPE_SUCCESS';
export const GET_ALL_ABSENCEREQUEST_BY_ABSENCETYPE_FAILURE = 'GET_ALL_ABSENCEREQUEST_BY_ABSENCETYPE_FAILURE';
