// ADD
export const ADD_CONTACTBYOPERATION = 'ADD_CONTACTBYOPERATION';
export const ADD_CONTACTBYOPERATION_SUCCESS = 'ADD_CONTACTBYOPERATION_SUCCESS';
export const ADD_CONTACTBYOPERATION_FAILURE = 'ADD_CONTACTBYOPERATION_FAILURE';

// UPDATE
export const UPDATE_CONTACTBYOPERATION = 'UPDATE_CONTACTBYOPERATION';
export const UPDATE_CONTACTBYOPERATION_SUCCESS = 'UPDATE_CONTACTBYOPERATION_SUCCESS';
export const UPDATE_CONTACTBYOPERATION_FAILURE = 'UPDATE_CONTACTBYOPERATION_FAILURE';

// DELETE
export const DELETE_CONTACTBYOPERATION = 'DELETE_CONTACTBYOPERATION';
export const DELETE_CONTACTBYOPERATION_SUCCESS = 'DELETE_CONTACTBYOPERATION_SUCCESS';
export const DELETE_CONTACTBYOPERATION_FAILURE = 'DELETE_CONTACTBYOPERATION_FAILURE';

// GET ALL
export const GET_ALL_CONTACTBYOPERATIONS = 'GET_ALL_CONTACTBYOPERATIONS';
export const GET_ALL_CONTACTBYOPERATIONS_SUCCESS = 'GET_ALL_CONTACTBYOPERATIONS_SUCCESS';
export const GET_ALL_CONTACTBYOPERATIONS_FAILURE = 'GET_ALL_CONTACTBYOPERATIONS_FAILURE';

// GET ONE
export const GET_ONE_CONTACTBYOPERATIONS = 'GET_ONE_CONTACTBYOPERATIONS';
export const GET_ONE_CONTACTBYOPERATIONS_SUCCESS = 'GET_ONE_CONTACTBYOPERATIONS_SUCCESS';
export const GET_ONE_CONTACTBYOPERATIONS_FAILURE = 'GET_ONE_CONTACTBYOPERATIONS_FAILURE';
