// ADD
export const ADD_STAFF = 'ADD_STAFF';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAILURE = 'ADD_STAFF_FAILURE';

// UPDATE
export const UPDATE_STAFF = 'UPDATE_STAFF';
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS';
export const UPDATE_STAFF_FAILURE = 'UPDATE_STAFF_FAILURE';

// DELETE
export const DELETE_STAFF = 'DELETE_STAFF';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAILURE = 'DELETE_STAFF_FAILURE';

// GET ALL
export const GET_ALL_STAFFS = 'GET_ALL_STAFFS';
export const GET_ALL_STAFFS_SUCCESS = 'GET_ALL_STAFFS_SUCCESS';
export const GET_ALL_STAFFS_FAILURE = 'GET_ALL_STAFFS_FAILURE';

// GET ALL ASSIGNED FUNCTIONAL LEVEL STAFFS
export const GET_ALL_ASSIGNED_FUNCTIONAL_LEVEL_STAFFS = 'GET_ALL_ASSIGNED_FUNCTIONAL_LEVEL_STAFFS';
export const GET_ALL_ASSIGNED_FUNCTIONAL_LEVEL_STAFFS_SUCCESS = 'GET_ALL_ASSIGNED_FUNCTIONAL_LEVEL_STAFFS_SUCCESS';
export const GET_ALL_ASSIGNED_FUNCTIONAL_LEVEL_STAFFS_FAILURE = 'GET_ALL_ASSIGNED_FUNCTIONAL_LEVEL_STAFFS_FAILURE';

export const SET_EDIT = 'SET_EDIT';
export const SET_STAFF = 'SET_STAFF';

// GET STAFF BY COMPANY EMAIL
export const GET_STAFF_BY_COMPANY_EMAIL = 'GET_STAFF_BY_COMPANY_EMAIL';
export const GET_STAFF_BY_COMPANY_EMAIL_SUCCESS = 'GET_STAFF_BY_COMPANY_EMAIL_SUCCESS';
export const GET_STAFF_BY_COMPANY_EMAIL_FAILURE = 'GET_STAFF_BY_COMPANY_EMAIL_FAILURE';


// GET WITH PAGINATION
export const GET_PAGINATION_STAFFS = 'GET_PAGINATION_STAFFS';
export const GET_PAGINATION_STAFFS_SUCCESS = 'GET_PAGINATION_STAFFS_SUCCESS';
export const GET_PAGINATION_STAFFS_FAILURE = 'GET_PAGINATION_STAFFS_FAILURE';
