// ADD
export const ADD_LOCALBANKHOLIDAY = 'ADD_LOCALBANKHOLIDAY';
export const ADD_LOCALBANKHOLIDAY_SUCCESS = 'ADD_LOCALBANKHOLIDAY_SUCCESS';
export const ADD_LOCALBANKHOLIDAY_FAILURE = 'ADD_LOCALBANKHOLIDAY_FAILURE';

// UPDATE
export const UPDATE_LOCALBANKHOLIDAY = 'UPDATE_LOCALBANKHOLIDAY';
export const UPDATE_LOCALBANKHOLIDAY_SUCCESS = 'UPDATE_LOCALBANKHOLIDAY_SUCCESS';
export const UPDATE_LOCALBANKHOLIDAY_FAILURE = 'UPDATE_LOCALBANKHOLIDAY_FAILURE';

// DELETE
export const DELETE_LOCALBANKHOLIDAY = 'DELETE_LOCALBANKHOLIDAY';
export const DELETE_LOCALBANKHOLIDAY_SUCCESS = 'DELETE_LOCALBANKHOLIDAY_SUCCESS';
export const DELETE_LOCALBANKHOLIDAY_FAILURE = 'DELETE_LOCALBANKHOLIDAY_FAILURE';

// GET ALL
export const GET_ALL_LOCALBANKHOLIDAYS = 'GET_ALL_LOCALBANKHOLIDAYS';
export const GET_ALL_LOCALBANKHOLIDAYS_SUCCESS = 'GET_ALL_LOCALBANKHOLIDAYS_SUCCESS';
export const GET_ALL_LOCALBANKHOLIDAYS_FAILURE = 'GET_ALL_LOCALBANKHOLIDAYS_FAILURE';

// GET ALL BY COMPANY
export const GET_ALL_LOCALBANKHOLIDAYS_BY_COMPANY = 'GET_ALL_LOCALBANKHOLIDAYS_BY_COMPANY';
export const GET_ALL_LOCALBANKHOLIDAYS_BY_COMPANY_SUCCESS = 'GET_ALL_LOCALBANKHOLIDAYS_BY_COMPANY_SUCCESS';
export const GET_ALL_LOCALBANKHOLIDAYS_BY_COMPANY_FAILURE = 'GET_ALL_LOCALBANKHOLIDAYS_BY_COMPANY_FAILURE';
