// ADD EXPENSE STATUS
export const ADD_EXPENSE_STATUS = 'ADD_EXPENSE_STATUS';
export const ADD_EXPENSE_STATUS_FAILURE = 'ADD_EXPENSE_STATUS_FAILURE';
export const ADD_EXPENSE_STATUS_SUCCESS = 'ADD_EXPENSE_STATUS_SUCCESS';

// UPDATE EXPENSE STATUS
export const UPDATE_EXPENSE_STATUS = 'UPDATE_EXPENSE_STATUS';
export const UPDATE_EXPENSE_STATUS_FAILURE = 'UPDATE_EXPENSE_STATUS_FAILURE';
export const UPDATE_EXPENSE_STATUS_SUCCESS = 'UPDATE_EXPENSE_STATUS_SUCCESS';

// DELETE EXPENSE STATUS
export const DELETE_EXPENSE_STATUS = 'DELETE_EXPENSE_STATUS';
export const DELETE_EXPENSE_STATUS_FAILURE = 'DELETE_EXPENSE_STATUS_FAILURE';
export const DELETE_EXPENSE_STATUS_SUCCESS = 'DELETE_EXPENSE_STATUS_SUCCESS';

// GET ALL EXPENSES STATUS
export const GET_ALL_EXPENSES_STATUS = 'GET_ALL_EXPENSES_STATUS';
export const GET_ALL_EXPENSES_STATUS_FAILURE = 'GET_ALL_EXPENSES_STATUS_FAILURE';
export const GET_ALL_EXPENSES_STATUS_SUCCESS = 'GET_ALL_EXPENSES_STATUS_SUCCESS';
