// ADD EMAIL ADDRESS
export const ADD_TRAVEL_REQUEST_EMAIL_ADDRESS = 'ADD_TRAVEL_REQUEST_EMAIL_ADDRESS';
export const ADD_TRAVEL_REQUEST_EMAIL_ADDRESS_FAILURE = 'ADD_TRAVEL_REQUEST_EMAIL_ADDRESS_FAILURE';
export const ADD_TRAVEL_REQUEST_EMAIL_ADDRESS_SUCCESS = 'ADD_TRAVEL_REQUEST_EMAIL_ADDRESS_SUCCESS';

// UPDATE EMAIL ADDRESS
export const UPDATE_TRAVEL_REQUEST_EMAIL_ADDRESS = 'UPDATE_TRAVEL_REQUEST_EMAIL_ADDRESS';
export const UPDATE_TRAVEL_REQUEST_EMAIL_ADDRESS_FAILURE = 'UPDATE_TRAVEL_REQUEST_EMAIL_ADDRESS_FAILURE';
export const UPDATE_TRAVEL_REQUEST_EMAIL_ADDRESS_SUCCESS = 'UPDATE_TRAVEL_REQUEST_EMAIL_ADDRESS_SUCCESS';


// DELETE EMAIL ADDRESS
export const DELETE_TRAVEL_REQUEST_EMAIL_ADDRESS = 'DELETE_TRAVEL_REQUEST_EMAIL_ADDRESS';
export const DELETE_TRAVEL_REQUEST_EMAIL_ADDRESS_FAILURE = 'DELETE_TRAVEL_REQUEST_EMAIL_ADDRESS_FAILURE';
export const DELETE_TRAVEL_REQUEST_EMAIL_ADDRESS_SUCCESS = 'DELETE_TRAVEL_REQUEST_EMAIL_ADDRESS_SUCCESS';

// GET ALL EMAIL ADDRESSES
export const GET_ALL_TRAVEL_REQUEST_EMAIL_ADDRESSES = 'GET_ALL_TRAVEL_REQUEST_EMAIL_ADDRESSES';
export const GET_ALL_TRAVEL_REQUEST_EMAIL_ADDRESSES_FAILURE = 'GET_ALL_TRAVEL_REQUEST_EMAIL_ADDRESSES_FAILURE';
export const GET_ALL_TRAVEL_REQUEST_EMAIL_ADDRESSES_SUCCESS = 'GET_ALL_TRAVEL_REQUEST_EMAIL_ADDRESSES_SUCCESS';
