// ADD
export const ADD_COMMERCIALOPERATION = 'ADD_COMMERCIALOPERATION';
export const ADD_COMMERCIALOPERATION_SUCCESS = 'ADD_COMMERCIALOPERATION_SUCCESS';
export const ADD_COMMERCIALOPERATION_FAILURE = 'ADD_COMMERCIALOPERATION_FAILURE';

// UPDATE
export const UPDATE_COMMERCIALOPERATION = 'UPDATE_COMMERCIALOPERATION';
export const UPDATE_COMMERCIALOPERATION_SUCCESS = 'UPDATE_COMMERCIALOPERATION_SUCCESS';
export const UPDATE_COMMERCIALOPERATION_FAILURE = 'UPDATE_COMMERCIALOPERATION_FAILURE';

// DELETE
export const DELETE_COMMERCIALOPERATION = 'DELETE_COMMERCIALOPERATION';
export const DELETE_COMMERCIALOPERATION_SUCCESS = 'DELETE_COMMERCIALOPERATION_SUCCESS';
export const DELETE_COMMERCIALOPERATION_FAILURE = 'DELETE_COMMERCIALOPERATION_FAILURE';

// GET ALL
export const GET_ALL_COMMERCIALOPERATIONS = 'GET_ALL_COMMERCIALOPERATIONS';
export const GET_ALL_COMMERCIALOPERATIONS_SUCCESS = 'GET_ALL_COMMERCIALOPERATIONS_SUCCESS';
export const GET_ALL_COMMERCIALOPERATIONS_FAILURE = 'GET_ALL_COMMERCIALOPERATIONS_FAILURE';
